# Generated by Django 2.0.5 on 2018-05-19 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('content', models.TextField()),
                ('tags', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('author', models.CharField(default='none', max_length=100)),
                ('author_id', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('post_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
