# Generated by Django 2.0.5 on 2018-05-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20180519_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='author_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='post',
            name='author_name',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
