# Generated by Django 2.0.5 on 2018-05-20 17:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_id', models.IntegerField(default=-1)),
                ('answer', models.TextField(default='No Answer', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_flag', models.BooleanField(default=False)),
                ('like_author_id', models.IntegerField(default=-1)),
                ('like_to_post_author_id', models.IntegerField(default=-1)),
                ('like_post_id', models.IntegerField(default=-1)),
                ('like_author', models.CharField(default='none', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('message', models.TextField()),
                ('by', models.CharField(default='none', max_length=200)),
                ('viewed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=500)),
                ('question_post_id', models.IntegerField(default=-1)),
                ('question_author_id', models.IntegerField(default=-1)),
                ('question_asker', models.CharField(max_length=200)),
                ('answer_flag', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_to_post_author_id',
            field=models.IntegerField(default=-1),
        ),
    ]
