# Generated by Django 2.0.5 on 2018-05-20 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20180520_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment_to_post_title',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='like',
            name='like_post_title',
            field=models.CharField(default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='notification',
            name='post_title',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
